#numpy

* numpy is  a multdin array

#the basics

#initialize array

In [48]:
import numpy as np

#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [49]:
import numpy as np


#initialize array

In [50]:
#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [51]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [52]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)


dimension of a : 1
dimension of b : 2


In [53]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)

shape of a : (3,)
shape of b : (2, 4)


In [54]:
#Get  Type
print("a type is :",a.dtype)

a type is : int16


In [55]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;


size of a : 3


In [56]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

In [57]:
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

np.float64(4.2)

In [58]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

row : [2.1]


In [59]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [60]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [61]:
#change element
b[1,2]=8
print(b)

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


In [62]:

b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [63]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  9.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

# 3-d example

In [64]:
c=np.array([[
             [1,2],[3,4]
             ],
             [
             [5,6],[7,8]
             ]
             ])

In [65]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [66]:
type (c)

numpy.ndarray

In [67]:
c.ndim

3

In [68]:
c.shape

(2, 2, 2)

In [69]:
c.size

8

## calculate the memory space took for c numpy array

In [70]:
c.dtype

dtype('int64')

In [71]:
c.itemsize *c.size

64

In [72]:
#get specific element (work outside in)
print ("specified element is :",c[1,1,0])

specified element is : 7


In [73]:
c[1,1,0]=100
c

array([[[  1,   2],
        [  3,   4]],

       [[  5,   6],
        [100,   8]]])

Initializing Different Types of Array

In [74]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
zm = np.zeros((3,4))

In [76]:
zm.ndim

2

In [77]:
zm.shape

(3, 4)

#All 1's matrix

In [78]:
ones = np.ones((4,3),dtype="int16")

In [79]:
ones[1,1]=100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1],
       [  1,   1,   1]], dtype=int16)

In [80]:
#any other number
np.full(ones.shape,88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [81]:
#any other number
np.full((4,5),100,dtype="float")

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

### reuse the already existing array and assign one value to en

In [82]:
np.full_like(ones,200,dtype="float")

array([[200., 200., 200.],
       [200., 200., 200.],
       [200., 200., 200.],
       [200., 200., 200.]])

### Random matrix

In [83]:
np.random.random_sample((2,3))

array([[0.54506901, 0.30710491, 0.73974428],
       [0.77614231, 0.73933492, 0.85177793]])

In [84]:
np.random.rand(2,4)

array([[0.01777844, 0.67891145, 0.63941224, 0.68127139],
       [0.19927033, 0.43850709, 0.65096367, 0.28304719]])

In [85]:
np.random.randint(2,9,size=(3,3))

array([[6, 7, 4],
       [5, 4, 3],
       [2, 8, 8]], dtype=int32)

In [87]:
#generate identity matrix only one argument bcoz identity matrix is
np.identity(5)#5,5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])